[package]
name = "leptodon-proc-macros"
description = "Procedural macros crate for Leptodon (your Leptos UI toolkit)."
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true
publish = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
quote = { workspace = true }
proc-macro2 = { workspace = true }
syn = { workspace = true, features = ["full"] }

[build-dependencies]
walkdir = "2.5.0"
