apiVersion: v1
kind: Pod
metadata:
  labels:
    ci: leptodon-build
spec:
  volumes:
    - name: dockerconfig
      secret:
        secretName: oa-sa-jenkins-registry-config
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:v1.23.1-debug
      resources:
        limits:
          memory: "16Gi"
          ephemeral-storage: "30Gi"
        requests:
          memory: "14Gi"
          cpu: 1
          ephemeral-storage: "30Gi"
      imagePullPolicy: Always
    - name: leptodon-build
      # Essentially an extended nixpkgs/nix-flakes image with some preinstalled CI and rust tooling.
      image: registry.openanalytics.eu/openanalytics/leptodon-build
      resources:
        limits:
          memory: "12Gi"
          ephemeral-storage: "30Gi"
          cpu: 7
        requests:
          memory: "8Gi"
          ephemeral-storage: "30Gi"
          cpu: 1
      tty: true
      securityContext:
        privileged: true
      volumeMounts:
        - name: dockerconfig
          mountPath: /root/.docker/config.json
          subPath: data
      command:
        - cat
      imagePullPolicy: Always
