apiVersion: v1
kind: Pod
metadata:
  labels:
    ci: leptodon-build
spec:
  hostUsers: false
  volumes:
    - name: dockerconfig
      secret:
        secretName: oa-sa-jenkins-registry-config
    - name: dshm
      emptyDir:
        medium: Memory
  containers:
    - name: leptodon-build
      # Essentially an extended nixpkgs/nix-flakes image with some preinstalled CI and rust tooling.
      image: registry.openanalytics.eu/openanalytics/leptodon-build
      resources:
        limits:
          memory: "12Gi"
          ephemeral-storage: "30Gi"
          cpu: 7
        requests:
          memory: "8Gi"
          ephemeral-storage: "30Gi"
          cpu: 1
      tty: true
      volumeMounts:
        - name: dockerconfig
          mountPath: /root/.docker/config.json
          subPath: data
        - name: dshm
          mountPath: /dev/shm
      command:
        - cat
      imagePullPolicy: Always
