services:
  front-end:
    build:
      context: ./
      dockerfile: ./overview.dev.Dockerfile
    restart: unless-stopped
    hostname: components-overview
    container_name: components-overview
    environment:
      - LEPTOS_SITE_ROOT=/tmp/target
      - LEPTOS_SITE_ADDR=0.0.0.0:8080
      - LEPTOS_RELOAD_EXTERNAL_PORT=80 # https://github.com/jvanmalder/leptos/commit/271154d6809f836a743dec603eb714d78ec8f6bd
      - CARGO_TARGET_DIR=/tmp/target # https://github.com/leptos-rs/cargo-leptos/issues/74
      - CARGO_BUILD_TARGET_DIR=/tmp/target # https://github.com/leptos-rs/cargo-leptos/issues/74
      - RUST_LOG=info
      - SCCACHE_DIR=/tmp/sccache
      - RUSTC_WRAPPER=/usr/local/bin/sccache
      - TS_DATABASE__URL=sqlite:/tmp/target/sessions.db
    # - RUST_BACKTRACE=1
    ports:
      - 8080:8080
    volumes:
      - ./:/tmp/leptos-components:ro
      - ./common:/tmp/common:ro
      - front-end-target:/tmp/target
      - front-end-cache:/usr/local/cargo/registry/cache
      - front-end-sccache:/tmp/sccache
      - front-end-node-modules:/tmp/overview/node_modules/
    command:
      - sh
      - -c
      - cd /tmp/leptos-components/overview && npm install --no-package-lock && cargo leptos watch
volumes:
  logs:
  front-end-target:
  front-end-cache:
  front-end-sccache:
  front-end-node-modules:
