[tasks.license-check]
workspace = false
command = "licensure"
args = ["--check", "--project"]

# Builds
[tasks.build-demo]
workspace = false
cwd = "demo"
command = "cargo"
args = ["leptos", "build", "--release", "--precompress", "-vv"]

# Lints
[tasks.lint-leptodon]
workspace = false
cwd = "./leptodon"
command = "cargo"
args = ["clippy", "--all-targets", "--all-features", "--", "-D", "warnings"]

[tasks.lint-test-overview]
workspace = false
cwd = "./overview"
command = "cargo"
args = ["clippy", "--all-targets", "--all-features", "--", "-D", "warnings"]

[tasks.lint-test-overview-codegen]
workspace = false
cwd = "./overview/codegen"
command = "cargo"
args = ["clippy", "--all-targets", "--all-features", "--", "-D", "warnings"]

[tasks.lint-demo]
workspace = false
cwd = "./demo"
command = "cargo"
args = ["clippy", "--all-targets", "--all-features", "--", "-D", "warnings"]

[tasks.lint-demo-codegen]
workspace = false
cwd = "./demo/codegen"
command = "cargo"
args = ["clippy", "--all-targets", "--all-features", "--", "-D", "warnings"]

[tasks.lint-demo-macros]
workspace = false
cwd = "./proc-macros"
command = "cargo"
args = ["clippy", "--all-targets", "--all-features", "--", "-D", "warnings"]

[tasks.lint]
workspace = false
run_task = { name = [
    "lint-leptodon",
    "lint-test-overview",
    "lint-test-overview-codegen",
    "lint-demo",
    "lint-demo-codegen",
    "lint-demo-macros",
] }

# Tests
[tasks.unit-tests]
workspace = false
cwd = "./leptodon"
command = "cargo"
args = ["nextest", "run", "-r"]

[tasks.integration-tests]
workspace = false
cwd = "./overview"
command = "cargo"
args = ["leptos", "end-to-end", "--precompress", "--release"]

[tasks.tests]
workspace = false
run_task = { name = [
    "unit-tests",
    "integration-tests"
] }

# Tries to run the same checks as the CI, locally.
[tasks.mimic-ci]
workspace = false
run_task = { name = [
    "license-check",
    "lint",
    "tests"
] }

# Publish tasks
[tasks.publish-if-missing]
workspace = false
script = '''
#!/bin/sh
set +e
crate=${1:-${PUBLISH_CRATE?Expecting <crate> argument or PUBLISH_CRATE env variable. E.g. leptodon, leptodon-proc-macros}}

# Source - https://stackoverflow.com/a/20460402
# Posted by F. Hauri  - Give Up GitHub, modified by community. See post 'Timeline' for change history
# Retrieved 2026-03-19, License - CC BY-SA 4.0
stringContain() { case $2 in *$1* ) return 0;; *) return 1;; esac ;}
# End

local_version=$(
    cargo info $crate -q --color never |\
        grep -oP '^version:\s*\K[^\s]+'
);
remote_version=$(
    cargo search --quiet --limit 1 --color never $crate |\
        grep -oP "$crate\s*=\s*\"\K[^\"]+"
);

if stringContain "dev" $local_version; then
    echo "Dev version '$local_version' detected.";
    echo "Skipping publishing of $crate.";
    exit 0;
fi

if [ "$local_version" != "$remote_version" ]; then
    echo "Local '$local_version' != '$remote_version'.";
    echo "Starting to publish.";
    cargo publish -p $crate;
else
    echo "Version already match!"
    echo "Skipping publishing of $crate.";
fi
'''

[tasks.publish-leptodon-if-missing]
workspace = false
env = { "PUBLISH_CRATE" = "leptodon" }
run_task = "publish-if-missing"

[tasks.publish-leptodon-proc-macros-if-missing]
workspace = false
env = { "PUBLISH_CRATE" = "leptodon-proc-macros" }
run_task = "publish-if-missing"