use leptos::web_sys;
use std::ops::Range;

use ::chrono::NaiveDate;
use leptos::IntoView;
use leptos::component;
use leptos::either::Either;
use leptos::prelude::ElementChild;
use leptos::view;

use leptodon::button::ControlButton;
use leptodon::class_list;
use leptodon::icon::EditIcon;
use leptodon::icon::Icon;
use leptodon::table::StyledHeadDragHandler;
use leptos::prelude::*;
use leptos_struct_table::*;

// Tables are implemented in the leptos-struct-table crate
// This file contains an example table for demonstrative purposes.

#[derive(Clone, Copy, Default, Debug)]
struct AdminEditButtonCell {
    is_admin: bool,
}

/// Arbitrary detail data
#[derive(Debug, Clone, Default)]
struct DetailData {
    show: bool,
    text: String,
}

#[derive(TableRow, Clone, Default, Debug)]
#[table(
    sortable,
    classes_provider = "TailwindClassesPreset",
    column_index_type = "enum",
    impl_vec_data_provider
)]
pub struct Person {
    #[table(renderer = "DetailCellRenderer", skip_sort)]
    detail: DetailData,
    id: u32,
    name: String,
    age: u32,
    date: NaiveDate,
    #[table(renderer = "AdminEditButtonCellRenderer", skip_sort)]
    _admin_editable: FieldGetter<AdminEditButtonCell>,
}

#[component]
fn DetailCellRenderer(
    class: String,
    value: Signal<DetailData>,
    row: RwSignal<Person>,
    index: PersonColumn,
) -> impl IntoView {
    let _ = index;
    view! {
        <td class=class_list!(class, "hover:cursor-pointer") on:click=move |_| {
            row.update(|old| {
                old.detail.show = !old.detail.show;
            });
        }>
            <Icon icon=leptodon::icon::DownIcon() class=class_list!(
                "w-3 h-3",
                ("-rotate-90", move || !value.get().show)
            ) />
        </td>
    }
}

#[allow(unused_variables, non_snake_case)]
pub fn DetailRowRenderer(
    // The class attribute for the row element. Generated by the classes provider.
    class: Signal<String>,
    // The row to render.
    row: RwSignal<Person>,
    // The index of the row. Starts at 0 for the first body row.
    index: usize,
    // The selected state of the row. True, when the row is selected.
    selected: Signal<bool>,
    // Event handler callback when this row is selected
    on_select: EventHandler<web_sys::MouseEvent>,
    // Columns to show and their order.
    columns: RwSignal<Vec<PersonColumn>>,
) -> impl IntoView
where {
    // debug_log!("Index of row: {}", index);
    // debug_log!("{:?}", row.get());
    let preset = TailwindClassesPreset {};
    leptos::view! {
        <tr class=class on:click=move |mouse_event| on_select.run(mouse_event) attr:data-testid=format!("person-row-{index}")>
            <For
                each=move || columns.get().into_iter()
                key=|column| *column
                children=move |column| {
                    Person::cell_renderer_for_column(row, column, format!("person-row-{index}-col-{column:?}")).into_any()
                }
            >
            </For>
        </tr>
        <tr class=class_list!(
            move || class.get(),
            ("hidden", move || !row.get().detail.show)
        )  attr:data-testid=format!("person-detail-{index}")>
            <td class= preset.cell("")> { move || row.get().detail.text }</td>

        </tr>
    }
}

#[component]
pub fn DemoTable() -> impl IntoView {
    let rows = get_person_rows();
    let preset = TailwindClassesPreset {};
    view! {
        <div> hello </div>
        <table data-testid="person-table">
            <TableContent rows
                scroll_container="html"
                drag_handler=HeadDragHandler::new(StyledHeadDragHandler)
                row_renderer=DetailRowRenderer
            />
            <tbody>
                <tr>
                    <td class=move || preset.cell("") colspan="5">A Footer</td>
                </tr>
            </tbody>
        </table>
    }
}

fn get_person_rows() -> Vec<Person> {
    let date = NaiveDate::from_ymd_opt(2025, 10, 10).unwrap();
    let admin_editable = FieldGetter::default();
    vec![
        Person {
            detail: DetailData {
                show: false,
                text: "Lemmens".to_string(),
            },
            id: 1,
            name: "John".to_string(),
            age: 32,
            date,
            _admin_editable: admin_editable,
        },
        Person {
            detail: DetailData {
                show: false,
                text: "Doe".to_string(),
            },
            id: 2,
            name: "Jane".to_string(),
            age: 28,
            date,
            _admin_editable: admin_editable,
        },
        Person {
            detail: DetailData {
                show: false,
                text: "Bob".to_string(),
            },
            id: 3,
            name: "Bob".to_string(),
            age: 45,
            date,
            _admin_editable: admin_editable,
        },
        Person {
            detail: DetailData {
                show: false,
                text: "Bob3".to_string(),
            },
            id: 4,
            name: "Bob".to_string(),
            age: 46,
            date,
            _admin_editable: admin_editable,
        },
        Person {
            detail: DetailData {
                show: false,
                text: "Bobbie".to_string(),
            },
            id: 5,
            name: "Bob".to_string(),
            age: 47,
            date,
            _admin_editable: admin_editable,
        },
        Person {
            detail: DetailData {
                show: false,
                text: "De bouwer".to_string(),
            },
            id: 6,
            name: "Bob".to_string(),
            age: 45,
            date,
            _admin_editable: admin_editable,
        },
    ]
}

impl Person {
    fn _admin_editable(&self) -> AdminEditButtonCell {
        AdminEditButtonCell { is_admin: true }
    }
}

impl TableDataProvider<Person, PersonColumn> for RwSignal<Vec<Person>> {
    async fn get_rows(&self, _: Range<usize>) -> Result<(Vec<Person>, Range<usize>), String> {
        let books = self.get_untracked().to_vec();
        let len = books.len();
        Ok((books, 0..len))
    }

    async fn row_count(&self) -> Option<usize> {
        Some(self.get_untracked().len())
    }
}

#[component]
fn AdminEditButtonCellRenderer(
    class: String,
    value: Signal<AdminEditButtonCell>,
    row: RwSignal<Person>,
    index: PersonColumn,
) -> impl IntoView {
    let (_, _) = (row, index);
    view! {
        <td class=class>
            {move || if value.get().is_admin {
                Either::Left(view! {
                    <ControlButton icon=EditIcon() on_click=move |_| {}/>
                })
            } else {
                Either::Right(())
            }}
        </td>
    }
}
