pub mod include_generated;

#[cfg(feature = "leptos")]
pub mod accordion;
#[cfg(feature = "leptos")]
pub mod avatar;
#[cfg(feature = "leptos")]
pub mod badge;
#[cfg(feature = "leptos")]
pub mod button;
#[cfg(feature = "leptos")]
pub mod button_group;
#[cfg(feature = "leptos")]
pub mod calendar;
#[cfg(feature = "leptos")]
pub mod checkbox;
#[cfg(feature = "leptos")]
pub mod class_list;
#[cfg(feature = "leptos")]
pub mod darkmode;
#[cfg(feature = "leptos")]
pub mod date_picker;
#[cfg(feature = "leptos")]
pub mod dialog;
#[cfg(feature = "leptos")]
pub mod dropdown;
#[cfg(feature = "leptos")]
pub mod form_input;
#[cfg(feature = "leptos")]
pub mod icon;
#[cfg(feature = "leptos")]
pub mod input;
#[cfg(feature = "leptos")]
pub mod input_group;
#[cfg(feature = "leptos")]
pub mod link;
#[cfg(feature = "leptos")]
pub mod modal;
#[cfg(feature = "leptos")]
pub mod navbar;
#[cfg(feature = "leptos")]
pub mod popover;
#[cfg(feature = "leptos")]
pub mod radio;
#[cfg(feature = "leptos")]
pub mod select;
#[cfg(feature = "leptos")]
pub mod spinner;
#[cfg(feature = "leptos")]
pub mod table;
#[cfg(feature = "leptos")]
pub mod tag_picker;
#[cfg(feature = "leptos")]
pub mod textarea;
#[cfg(feature = "leptos")]
pub mod toggle;
#[cfg(feature = "leptos")]
pub mod util;
